# Site settings
title: Julia Himmel
email: himmel.julia@gmail.com
description: "Here you will find my thoughts on web development."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
